var animaldb = new Object()

animaldb["Dog"] = [{value:"Affenpinscher", text:"Affenpinscher"},
					{value:"Afghan Hound", text: "Afghan Hound"},
					{value:"African Boerboel", text: "African Boerboel"},
					{value:"Airedale Terrier", text: "Airedale Terrier"},
					{value:"Akbash Dog", text: "Akbash Dog"},
					{value:"Akita", text: "Akita"},
					{value:"Alapha Blue Blood Bulldog", text: "Alapha Blue Blood Bulldog"},
					{value:"Alaskan Klee Kai", text: "Alaskan Klee Kai"},
					{value:"Alaskan Malamute", text: "Alaskan Malamute"},
					{value:"American Bandogge Mastiff", text: "American Bandogge Mastiff"},
					{value:"American Bulldog", text: "American Bulldog"},
					{value:"American Eskimo", text: "American Eskimo"},
					{value:"American Foxhound", text: "American Foxhound"},
					{value:"American Pit Bull Terrier", text: "American Pit Bull Terrier"},
					{value:"American Staffordshire Terrier", text: "American Staffordshire Terrier"},
					{value:"American Water Spaniel", text: "American Water Spaniel"},
					{value:"Anatolian Shepherd", text: "Anatolian Shepherd"},
					{value:"Australian Cattle Dog", text: "Australian Cattle Dog"},
					{value:"Australian Kelpie", text: "Australian Kelpie"},
					{value:"Australian Shepherd", text: "Australian Shepherd"},
					{value:"Australian Terrier", text: "Australian Terrier"},
					{value:"Basenji", text: "Basenji"},
					{value:"Basset Hound", text: "Basset Hound"},
					{value:"Beagle", text: "Beagle"},
					{value:"Bearded Collie", text: "Bearded Collie"},
					{value:"Beauceron", text: "Beauceron"},
					{value:"Bedlington Terrier", text: "Bedlington Terrier"},
					{value:"Belgian Malinois", text: "Belgian Malinois"},
					{value:"Belgian Sheepdog", text: "Belgian Sheepdog"},
					{value:"Belgian Tervuren", text: "Belgian Tervuren"},
					{value:"Bernese Mountain Dog", text: "Bernese Mountain Dog"},
					{value:"Bichon Frise", text: "Bichon Frise"},
					{value:"Biewer Terrier", text: "Biewer Terrier"},
					{value:"Black and Tan Coonhound", text: "Black and Tan Coonhound"},
					{value:"Black Russian Terrier", text: "Black Russian Terrier"},
					{value:"Bloodhound", text: "Bloodhound"},
					{value:"Border Collie", text: "Border Collie"},
					{value:"Border Terrier", text: "Border Terrier"},
					{value:"Borzoi", text: "Borzoi"},
					{value:"Boston Terrier", text: "Boston Terrier"},
					{value:"Bouvier des Flandres", text: "Bouvier des Flandres"},
					{value:"Boxer", text: "Boxer"},
					{value:"Briard", text: "Briard"},
					{value:"Briquet Griffon Vendeen", text: "Briquet Griffon Vendeen"},
					{value:"Brittany", text: "Brittany"},
					{value:"Brussels Griffon", text: "Brussels Griffon"},
					{value:"Bull Terrier", text: "Bull Terrier"},
					{value:"Bullmastiff", text: "Bullmastiff"},
					{value:"Cairn Terrier", text: "Cairn Terrier"},
					{value:"Canaan Dog", text: "Canaan Dog"},
					{value:"Cane Corso Italian Mastiff", text: "Cane Corso Italian Mastiff"},
					{value:"Cardigan Welsh Corgi", text: "Cardigan Welsh Corgi"},
					{value:"Catahoula Leopard Dog", text: "Catahoula Leopard Dog"},
					{value:"Cavalier King Charles Spaniel", text: "Cavalier King Charles Spaniel"},
					{value:"Central Asian Ovtcharka", text: "Central Asian Ovtcharka"},
					{value:"Cesky Terrier", text: "Cesky Terrier"},
					{value:"Chesapeake Bay Retriever", text: "Chesapeake Bay Retriever"},
					{value:"Chihuahua", text: "Chihuahua"},
					{value:"Chinese Crested", text: "Chinese Crested"},
					{value:"Chinese Foo", text: "Chinese Foo"},
					{value:"Chinese Shar-Pei", text: "Chinese Shar-Pei"},
					{value:"Chow Chow", text: "Chow Chow"},
					{value:"Clumber Spaniel", text: "Clumber Spaniel"},
					{value:"Cocker Spaniel", text: "Cocker Spaniel"},
					{value:"Collie", text: "Collie"},
					{value:"Coton De Tulear", text: "Coton De Tulear"},
					{value:"Curly-Coated Retriever", text: "Curly-Coated Retriever"},
					{value:"Dachshund", text: "Dachshund"},
					{value:"Dalmatian", text: "Dalmatian"},
					{value:"Dandie Dinmont Terrier", text: "Dandie Dinmont Terrier"},
					{value:"Doberman Pinscher", text: "Doberman Pinscher"},
					{value:"Dogo Argentino", text: "Dogo Argentino"},
					{value:"Dogue de Bordeaux", text: "Dogue de Bordeaux"},
					{value:"English Bulldog", text: "English Bulldog"},
					{value:"English Cocker Spaniel", text: "English Cocker Spaniel"},
					{value:"English Foxhound", text: "English Foxhound"},
					{value:"English Setter", text: "English Setter"},
					{value:"English Springer Spaniel", text: "English Springer Spaniel"},
					{value:"English Toy Spaniel", text: "English Toy Spaniel"},
					{value:"Estrela Mountain Dog", text: "Estrela Mountain Dog"},
					{value:"Field Spaniel", text: "Field Spaniel"},
					{value:"Fila Brasileiro", text: "Fila Brasileiro"},
					{value:"Finnish Spitz", text: "Finnish Spitz"},
					{value:"Flat-Coated Retriever", text: "Flat-Coated Retriever"},
					{value:"Fox Terrier (Smooth)", text: "Fox Terrier (Smooth)"},
					{value:"Fox Terrier (Wire)", text: "Fox Terrier (Wire)"},
					{value:"French Bulldog", text: "French Bulldog"},
					{value:"German Pinscher", text: "German Pinscher"},
					{value:"German Shepherd Dog", text: "German Shepherd Dog"},
					{value:"German Shorthaired Pointer", text: "German Shorthaired Pointer"},
					{value:"German Wirehaired Pointer", text: "German Wirehaired Pointer"},
					{value:"Giant Schnauzer", text: "Giant Schnauzer"},
					{value:"Golden Retriever", text: "Golden Retriever"},
					{value:"Gordon Setter", text: "Gordon Setter"},
					{value:"Great Dane", text: "Great Dane"},
					{value:"Great Pyrenee", text: "Great Pyrenee"},
					{value:"Greater Swiss Mountain Dog", text: "Greater Swiss Mountain Dog"},
					{value:"Greyhound", text: "Greyhound"},
					{value:"Harrier", text: "Harrier"},
					{value:"Havanese", text: "Havanese"},
					{value:"Ibizan Hound", text: "Ibizan Hound"},
					{value:"Irish Setter", text: "Irish Setter"},
					{value:"Irish Terrier", text: "Irish Terrier"},
					{value:"Irish Water Spaniel", text: "Irish Water Spaniel"},
					{value:"Irish Wolfhound", text: "Irish Wolfhound"},
					{value:"Italian Greyhound", text: "Italian Greyhound"},
					{value:"Jack Russell Terrier", text: "Jack Russell Terrier"},
					{value:"Japanese Chin", text: "Japanese Chin"},
					{value:"Karelian Bear Dog", text: "Karelian Bear Dog"},
					{value:"Keeshond", text: "Keeshond"},
					{value:"Kerry Blue Terrier", text: "Kerry Blue Terrier"},
					{value:"Komondor", text: "Komondor"},
					{value:"Kooikerhondje", text: "Kooikerhondje"},
					{value:"Kuvasz", text: "Kuvasz"},
					{value:"Labrador Retriever", text: "Labrador Retriever"},
					{value:"Laekenois", text: "Laekenois"},
					{value:"Lakeland Terrier", text: "Lakeland Terrier"},
					{value:"Lhasa Apso", text: "Lhasa Apso"},
					{value:"Lowchen", text: "Lowchen"},
					{value:"Maltese", text: "Maltese"},
					{value:"Manchester Terrier", text: "Manchester Terrier"},
					{value:"Maremma Sheepdog", text: "Maremma Sheepdog"},
					{value:"Mastiff", text: "Mastiff"},
					{value:"Miniature Australian Shepherd", text: "Miniature Australian Shepherd"},
					{value:"Miniature Bull Terrier", text: "Miniature Bull Terrier"},
					{value:"Miniature Pinscher", text: "Miniature Pinscher"},
					{value:"Miniature Poodle", text: "Miniature Poodle"},
					{value:"Miniature Schnauzer", text: "Miniature Schnauzer"},
					{value:"Neapolitan Mastiff", text: "Neapolitan Mastiff"},
					{value:"Newfoundland", text: "Newfoundland"},
					{value:"Norfolk Terrier", text: "Norfolk Terrier"},
					{value:"Norwegian Buhund", text: "Norwegian Buhund"},
					{value:"Norwegian Elkhound", text: "Norwegian Elkhound"},
					{value:"Norwich Terrier", text: "Norwich Terrier"},
					{value:"Nova Scotia Duck Tolling Retriever", text: "Nova Scotia Duck Tolling Retriever"},
					{value:"Old English Sheepdog", text: "Old English Sheepdog"},
					{value:"Otterhound", text: "Otterhound"},
					{value:"Papillon", text: "Papillon"},
					{value:"Pekingese", text: "Pekingese"},
					{value:"Pembroke Welsh Corgi", text: "Pembroke Welsh Corgi"},
					{value:"Petit Basset Griffon Vendeen", text: "Petit Basset Griffon Vendeen"},
					{value:"Pharaoh Hound", text: "Pharaoh Hound"},
					{value:"Pointer", text: "Pointer"},
					{value:"Polish Owczarek Nizinny", text: "Polish Owczarek Nizinny"},
					{value:"Pomeranian", text: "Pomeranian"},
					{value:"Portuguese Water Dog", text: "Portuguese Water Dog"},
					{value:"Pug", text: "Pug"},
					{value:"Puli", text: "Puli"},
					{value:"Rat Terrier", text: "Rat Terrier"},
					{value:"Red and White Setter", text: "Red and White Setter"},
					{value:"Redbone Coonhound", text: "Redbone Coonhound"},
					{value:"Rhodesian Ridgeback", text: "Rhodesian Ridgeback"},
					{value:"Rottweiler", text: "Rottweiler"},
					{value:"Saint Bernard", text: "Saint Bernard"},
					{value:"Saluki", text: "Saluki"},
					{value:"Samoyed", text: "Samoyed"},
					{value:"Schipperke", text: "Schipperke"},
					{value:"Scottish Deerhound", text: "Scottish Deerhound"},
					{value:"Scottish Terrier", text: "Scottish Terrier"},
					{value:"Sealyham Terrier", text: "Sealyham Terrier"},
					{value:"Shetland Sheepdog", text: "Shetland Sheepdog"},
					{value:"Shiba-Inu", text: "Shiba-Inu"},
					{value:"Shih Tzu", text: "Shih Tzu"},
					{value:"Siberian Husky", text: "Siberian Husky"},
					{value:"Silky Terrier", text: "Silky Terrier"},
					{value:"Skye Terrier", text: "Skye Terrier"},
					{value:"Soft Coated Wheaten Terrier", text: "Soft Coated Wheaten Terrier"},
					{value:"Spinone Italiano", text: "Spinone Italiano"},
					{value:"Staffordshire Bull Terrier", text: "Staffordshire Bull Terrier"},
					{value:"Standard Poodle", text: "Standard Poodle"},
					{value:"Standard Schnauzer", text: "Standard Schnauzer"},
					{value:"Sussex Spaniel", text: "Sussex Spaniel"},
					{value:"Tibetan Spaniel", text: "Tibetan Spaniel"},
					{value:"Tibetan Terrier", text: "Tibetan Terrier"},
					{value:"Toy Fox Terrier", text: "Toy Fox Terrier"},
					{value:"Toy Manchester Terrier", text: "Toy Manchester Terrier"},
					{value:"Toy Poodle", text: "Toy Poodle"},
					{value:"Vizsla", text: "Vizsla"},
					{value:"Weimaraner", text: "Weimaraner"},
					{value:"Welsh Springer Spaniel", text: "Welsh Springer Spaniel"},
					{value:"Welsh Terrier", text: "Welsh Terrier"},
					{value:"West Highland White Terrier", text: "West Highland White Terrier"},
					{value:"Whippet", text: "Whippet"},
					{value:"Wire Fox Terrier", text: "Wire Fox Terrier"},
					{value:"Wirehaired Pointing Griffon", text: "Wirehaired Pointing Griffon"},
					{value:"Xoloitzcuintli", text: "Xoloitzcuintli"},
					{value:"Yorkshire Terrier", text: "Yorkshire Terrier"}];
					  
	
animaldb["Cat"] = [{value:"Not Applicable", text:"Not Applicable"}];
	
animaldb["Goat"] = [{value:"Alpine", text:"Alpine"},
					{value:"Altai Mountain", text: "Altai Mountain"},
					{value:"American Cashmere", text: "American Cashmere"},
					{value:"Anatolian Black", text: "Anatolian Black"},
					{value:"Anglo-Nubian (Nubian)", text: "Anglo-Nubian (Nubian)"},
					{value:"Angora", text: "Angora"},
					{value:"Appenzell", text: "Appenzell"},
					{value:"Arapawa Island", text: "Arapawa Island"},
					{value:"Australian Goat", text: "Australian Goat"},
					{value:"Bagot", text: "Bagot"},
					{value:"Barbari", text: "Barbari"},
					{value:"Beetal", text: "Beetal"},
					{value:"Belgian Fawn", text: "Belgian Fawn"},
					{value:"Benadir", text: "Benadir"},
					{value:"Bhuj", text: "Bhuj"},
					{value:"Bionda dell'Adamello", text: "Bionda dell'Adamello"},
					{value:"Black Bengal", text: "Black Bengal"},
					{value:"Boer", text: "Boer"},
					{value:"Booted Goat", text: "Booted Goat"},
					{value:"British Alpine", text: "British Alpine"},
					{value:"Brown Shorthair Goat", text: "Brown Shorthair Goat"},
					{value:"Canary Island", text: "Canary Island"},
					{value:"Canindé", text: "Canindé"},
					{value:"Carpathian", text: "Carpathian"},
					{value:"Chamois Colored", text: "Chamois Colored"},
					{value:"Changthangi", text: "Changthangi"},
					{value:"Chappar", text: "Chappar"},
					{value:"Charnequeira", text: "Charnequeira"},
					{value:"Chengde Polled", text: "Chengde Polled"},
					{value:"Chengdu Brown", text: "Chengdu Brown"},
					{value:"Chigu", text: "Chigu"},
					{value:"Corsican", text: "Corsican"},
					{value:"Daera Din Panah", text: "Daera Din Panah"},
					{value:"Damani", text: "Damani"},
					{value:"Damascus", text: "Damascus"},
					{value:"Danish Landrace", text: "Danish Landrace"},
					{value:"Don", text: "Don"},
					{value:"Duan", text: "Duan"},
					{value:"Dutch Landrace", text: "Dutch Landrace"},
					{value:"Dutch Toggenburg", text: "Dutch Toggenburg"},
					{value:"Erzgebirg", text: "Erzgebirg"},
					{value:"Finnish Landrace", text: "Finnish Landrace"},
					{value:"Girgentana", text: "Girgentana"},
					{value:"Göingeget", text: "Göingeget"},
					{value:"Golden Guernsey", text: "Golden Guernsey"},
					{value:"Grisons Striped", text: "Grisons Striped"},
					{value:"Hailun", text: "Hailun"},
					{value:"Haimen", text: "Haimen"},
					{value:"Hasi", text: "Hasi"},
					{value:"Hejazi", text: "Hejazi"},
					{value:"Hexi Cashmere", text: "Hexi Cashmere"},
					{value:"Hongtong", text: "Hongtong"},
					{value:"Huaipi", text: "Huaipi"},
					{value:"Huaitoutala", text: "Huaitoutala"},
					{value:"Hungarian Improved ", text: "Hungarian Improved "},
					{value:"Irish Goat", text: "Irish Goat"},
					{value:"Jining Grey", text: "Jining Grey"},
					{value:"Kaghani", text: "Kaghani"},
					{value:"Kamori", text: "Kamori"},
					{value:"Kiko", text: "Kiko"},
					{value:"Kinder", text: "Kinder"},
					{value:"LaMancha", text: "LaMancha"},
					{value:"Loashan", text: "Loashan"},
					{value:"Moxotó", text: "Moxotó"},
					{value:"Murcia-Granada", text: "Murcia-Granada"},
					{value:"Myotonic (Wooden Leg)", text: "Myotonic (Wooden Leg)"},
					{value:"Nachi", text: "Nachi"},
					{value:"Nigerian Dwarf", text: "Nigerian Dwarf"},
					{value:"Norwegian", text: "Norwegian"},
					{value:"Oberhasli", text: "Oberhasli"},
					{value:"Peacock Goat", text: "Peacock Goat"},
					{value:"Philippine", text: "Philippine"},
					{value:"Poitou", text: "Poitou"},
					{value:"Pygmy", text: "Pygmy"},
					{value:"Pyrenean", text: "Pyrenean"},
					{value:"Qinshan ", text: "Qinshan "},
					{value:"Repartida", text: "Repartida"},
					{value:"Russian White", text: "Russian White"},
					{value:"Saanen", text: "Saanen"},
					{value:"Sahelian", text: "Sahelian"},
					{value:"San Clemente", text: "San Clemente"},
					{value:"Somali", text: "Somali"},
					{value:"Spanish", text: "Spanish"},
					{value:"SRD", text: "SRD"},
					{value:"Swedish Landrace", text: "Swedish Landrace"},
					{value:"Tauernsheck", text: "Tauernsheck"},
					{value:"Tennessee Fainting", text: "Tennessee Fainting"},
					{value:"Thuringian", text: "Thuringian"},
					{value:"Toggenburg", text: "Toggenburg"},
					{value:"Uzbek Black", text: "Uzbek Black"},
					{value:"Valais Blackneck", text: "Valais Blackneck"},
					{value:"Verata ", text: "Verata "},
					{value:"West African Dwarf", text: "West African Dwarf"},
					{value:"White Shorthaired Goat", text: "White Shorthaired Goat"},
					{value:"Wooden Leg Goat", text: "Wooden Leg Goat"},
					{value:"Xinjiang", text: "Xinjiang"},
					{value:"Xuhai ", text: "Xuhai "},
					{value:"Yemen Mountain ", text: "Yemen Mountain "},
					{value:"Zalawadi", text: "Zalawadi"},
					{value:"Zhiwulin Black", text: "Zhiwulin Black"},
					{value:"Zhongwei", text: "Zhongwei"}];
					
animaldb["Cattle"] = [{value:"Africander", text:"Africander"},
					{value:"Albères", text:"Albères"},
					{value:"Alentejana", text:"Alentejana"},
					{value:"Allmogekor", text:"Allmogekor"},
					{value:"American", text:"American"},
					{value:"American White Park", text:"American White Park"},
					{value:"Amerifax", text:"Amerifax"},
					{value:"Amrit Mahal", text:"Amrit Mahal"},
					{value:"Anatolian Black", text:"Anatolian Black"},
					{value:"Andalusian Black", text:"Andalusian Black"},
					{value:"Andalusian Grey", text:"Andalusian Grey"},
					{value:"Angeln", text:"Angeln"},
					{value:"Angus", text:"Angus"},
					{value:"Ankole", text:"Ankole"},
					{value:"Ankole-Watusi", text:"Ankole-Watusi"},
					{value:"Argentine Criollo", text:"Argentine Criollo"},
					{value:"Asturian Mountain", text:"Asturian Mountain"},
					{value:"Asturian Valley", text:"Asturian Valley"},
					{value:"Aubrac", text:"Aubrac"},
					{value:"Aulie-Ata", text:"Aulie-Ata"},
					{value:"Australian Braford", text:"Australian Braford"},
					{value:"Australian Friesian Sahiwal", text:"Australian Friesian Sahiwal"},
					{value:"Australian Lowline", text:"Australian Lowline"},
					{value:"Australian Milking Zebu", text:"Australian Milking Zebu"},
					{value:"Ayrshire", text:"Ayrshire"},
					{value:"Azaouak", text:"Azaouak"},
					{value:"Bachaur", text:"Bachaur"},
					{value:"Baladi", text:"Baladi"},
					{value:"Baltana Romaneasca", text:"Baltana Romaneasca"},
					{value:"Barka", text:"Barka"},
					{value:"Barzona", text:"Barzona"},
					{value:"Bazadais", text:"Bazadais"},
					{value:"Béarnais", text:"Béarnais"},
					{value:"Beefalo", text:"Beefalo"},
					{value:"Beefmaker", text:"Beefmaker"},
					{value:"Beefmaster", text:"Beefmaster"},
					{value:"Belarus Red", text:"Belarus Red"},
					{value:"Belgian Blue", text:"Belgian Blue"},
					{value:"Belgian Red", text:"Belgian Red"},
					{value:"Belmont Adaptaur", text:"Belmont Adaptaur"},
					{value:"Belmont Red", text:"Belmont Red"},
					{value:"Belted Galloway", text:"Belted Galloway"},
					{value:"Bengali", text:"Bengali"},
					{value:"Berrendas", text:"Berrendas"},
					{value:"Bhagnari", text:"Bhagnari"},
					{value:"Blacksided Trondheim and Norland", text:"Blacksided Trondheim and Norland"},
					{value:"Blanca Cacereña", text:"Blanca Cacereña"},
					{value:"Blanco Orejinegro", text:"Blanco Orejinegro"},
					{value:"Blonde d'Aquitaine", text:"Blonde d'Aquitaine"},
					{value:"Bonsmara", text:"Bonsmara"},
					{value:"Boran", text:"Boran"},
					{value:"Bordelais", text:"Bordelais"},
					{value:"Braford", text:"Braford"},
					{value:"Brahman", text:"Brahman"},
					{value:"Brahmousin", text:"Brahmousin"},
					{value:"Brangus", text:"Brangus"},
					{value:"Braunvieh", text:"Braunvieh"},
					{value:"British White", text:"British White"},
					{value:"Brown Swiss", text:"Brown Swiss"},
					{value:"Busa", text:"Busa"},
					{value:"Cachena", text:"Cachena"},
					{value:"Canadienne", text:"Canadienne"},
					{value:"Canary Island", text:"Canary Island"},
					{value:"Canchim", text:"Canchim"},
					{value:"Carinthian Blond", text:"Carinthian Blond"},
					{value:"Caucasian", text:"Caucasian"},
					{value:"Channi", text:"Channi"},
					{value:"Charbray", text:"Charbray"},
					{value:"Charolais", text:"Charolais"},
					{value:"Chianina", text:"Chianina"},
					{value:"Chinampo", text:"Chinampo"},
					{value:"Chinese Black-and-White", text:"Chinese Black-and-White"},
					{value:"Cholistani", text:"Cholistani"},
					{value:"Corriente", text:"Corriente"},
					{value:"Costeño con Cuernos", text:"Costeño con Cuernos"},
					{value:"Dajal", text:"Dajal"},
					{value:"Damascus", text:"Damascus"},
					{value:"Damietta", text:"Damietta"},
					{value:"Dangi", text:"Dangi"},
					{value:"Danish Jersey", text:"Danish Jersey"},
					{value:"Danish Red", text:"Danish Red"},
					{value:"Deoni", text:"Deoni"},
					{value:"Devon", text:"Devon"},
					{value:"Dexter", text:"Dexter"},
					{value:"Dhanni", text:"Dhanni"},
					{value:"Dølafe", text:"Dølafe"},
					{value:"Droughtmaster", text:"Droughtmaster"},
					{value:"Dulong", text:"Dulong"},
					{value:"Dutch Belted", text:"Dutch Belted"},
					{value:"Dutch Friesian", text:"Dutch Friesian"},
					{value:"East Anatolian Red", text:"East Anatolian Red"},
					{value:"Enderby Island", text:"Enderby Island"},
					{value:"English Longhorn", text:"English Longhorn"},
					{value:"Estonian Red", text:"Estonian Red"},
					{value:"Evolène", text:"Evolène"},
					{value:"Fighting Bull", text:"Fighting Bull"},
					{value:"Fjall", text:"Fjall"},
					{value:"Finnish", text:"Finnish"},
					{value:"Florida Cracker/Pineywoods", text:"Florida Cracker/Pineywoods"},
					{value:"Fulani Sudanese", text:"Fulani Sudanese "},
					{value:"Galician Blond", text:"Galician Blond "},
					{value:"Galloway", text:"Galloway"},
					{value:"Gaolao", text:"Gaolao"},
					{value:"Gascon", text:"Gascon"},
					{value:"Gelbray", text:"Gelbray"},
					{value:"Gelbvieh", text:"Gelbvieh"},
					{value:"German Angus", text:"German Angus"},
					{value:"German Red Pied", text:"German Red Pied"},
					{value:"Gir", text:"Gir"},
					{value:"Glan", text:"Glan"},
					{value:"Gloucester", text:"Gloucester"},
					{value:"Gobra", text:"Gobra"},
					{value:"Greek Shorthorn", text:"Greek Shorthorn"},
					{value:"Greek Steppe", text:"Greek Steppe"},
					{value:"Groningen Whiteheaded", text:"Groningen Whiteheaded"},
					{value:"Gudali", text:"Gudali"},
					{value:"Guernsey", text:"Guernsey"},
					{value:"Guzerat", text:"Guzerat"},
					{value:"Hallikar", text:"Hallikar"},
					{value:"Hariana", text:"Hariana"},
					{value:"Hartón", text:"Hartón"},
					{value:"Hays Converter", text:"Hays Converter"},
					{value:"Hereford", text:"Hereford"},
					{value:"Herens", text:"Herens"},
					{value:"Highland", text:"Highland"},
					{value:"Hinterwald", text:"Hinterwald"},
					{value:"Holando-Argentino", text:"Holando-Argentino"},
					{value:"Holstein", text:"Holstein"},
					{value:"Horro", text:"Horro"},
					{value:"Hungarian Grey", text:"Hungarian Grey"},
					{value:"Icelandic", text:"Icelandic"},
					{value:"Illawarra", text:"Illawarra"},
					{value:"Indo-Brazilian", text:"Indo-Brazilian"},
					{value:"Irish Moiled", text:"Irish Moiled"},
					{value:"Israeli Holstein", text:"Israeli Holstein"},
					{value:"Israeli Red", text:"Israeli Red"},
					{value:"Istoben", text:"Istoben"},
					{value:"Jamaica Black", text:"Jamaica Black"},
					{value:"Jamaica Hope", text:"Jamaica Hope"},
					{value:"Jamaica Red", text:"Jamaica Red"},
					{value:"Jaulan", text:"Jaulan"},
					{value:"Jersey", text:"Jersey"},
					{value:"Kangayam", text:"Kangayam"},
					{value:"Kankrej", text:"Kankrej"},
					{value:"Karan Fries", text:"Karan Fries"},
					{value:"Karan Swiss", text:"Karan Swiss"},
					{value:"Kazakh", text:"Kazakh"},
					{value:"Kenwariya", text:"Kenwariya"},
					{value:"Kerry", text:"Kerry"},
					{value:"Kherigarh", text:"Kherigarh"},
					{value:"Khillari", text:"Khillari"},
					{value:"Kholmogory", text:"Kholmogory"},
					{value:"Kilis", text:"Kilis"},
					{value:"Krishna Valley", text:"Krishna Valley"},
					{value:"Kurdi", text:"Kurdi"},
					{value:"Kuri", text:"Kuri"},
					{value:"Latvian Brown", text:"Latvian Brown"},
					{value:"Limousin", text:"Limousin"},
					{value:"Limpurger", text:"Limpurger"},
					{value:"Lincoln Red", text:"Lincoln Red"},
					{value:"Lithuanian Red", text:"Lithuanian Red"},
					{value:"Lohani", text:"Lohani"},
					{value:"Lourdais", text:"Lourdais"},
					{value:"Luing", text:"Luing"},
					{value:"Madagascar Zebu", text:"Madagascar Zebu"},
					{value:"Maine Anjou", text:"Maine Anjou"},
					{value:"Malvi", text:"Malvi"},
					{value:"Mandalong", text:"Mandalong"},
					{value:"Marchigiana", text:"Marchigiana"},
					{value:"Maremmana", text:"Maremmana"},
					{value:"Masai", text:"Masai"},
					{value:"Mashona", text:"Mashona"},
					{value:"Maure", text:"Maure"},
					{value:"Mazandarani", text:"Mazandarani"},
					{value:"Meuse-Rhine-Yssel", text:"Meuse-Rhine-Yssel"},
					{value:"Mewati", text:"Mewati"},
					{value:"Milking Devon", text:"Milking Devon"},
					{value:"Milking Shorthorn", text:"Milking Shorthorn"},
					{value:"Mirandesa", text:"Mirandesa"},
					{value:"Modicana", text:"Modicana"},
					{value:"Mongolian", text:"Mongolian"},
					{value:"Montbéliard", text:"Montbéliard"},
					{value:"Morucha", text:"Morucha"},
					{value:"Murboden", text:"Murboden"},
					{value:"Murray Grey", text:"Murray Grey"},
					{value:"Muturu", text:"Muturu "},
					{value:"Nagori", text:"Nagori"},
					{value:"Nanyang", text:"Nanyang"},
					{value:"N'dama", text:"N'dama"},
					{value:"Nelore", text:"Nelore"},
					{value:"Nguni", text:"Nguni"},
					{value:"Nimari", text:"Nimari"},
					{value:"Normande", text:"Normande"},
					{value:"Norwegian Red", text:"Norwegian Red"},
					{value:"Ongole", text:"Ongole"},
					{value:"Orma Boran", text:"Orma Boran"},
					{value:"Oropa", text:"Oropa"},
					{value:"Ovambo", text:"Ovambo"},
					{value:"Parthenais", text:"Parthenais"},
					{value:"Philippine Native", text:"Philippine Native"},
					{value:"Polish Red", text:"Polish Red"},
					{value:"Polled Hereford", text:"Polled Hereford"},
					{value:"Ponwar", text:"Ponwar"},
					{value:"Piedmontese", text:"Piedmontese"},
					{value:"Pinzgauer", text:"Pinzgauer"},
					{value:"Qinchuan", text:"Qinchuan"},
					{value:"Rätien Gray", text:"Rätien Gray"},
					{value:"Rath", text:"Rath"},
					{value:"Rathi", text:"Rathi"},
					{value:"Red Angus", text:"Red Angus"},
					{value:"Red Brangus", text:"Red Brangus"},
					{value:"Red Fulani", text:"Red Fulani"},
					{value:"Red Pied Friesian", text:"Red Pied Friesian"},
					{value:"Red Poll", text:"Red Poll"},
					{value:"Red Polled Østland", text:"Red Polled Østland"},
					{value:"Red Sindhi", text:"Red Sindhi"},
					{value:"Red Steppe", text:"Red Steppe"},
					{value:"Reggiana", text:"Reggiana"},
					{value:"Retinta", text:"Retinta"},
					{value:"Rojhan", text:"Rojhan"},
					{value:"Romagnola", text:"Romagnola"},
					{value:"Romosinuano", text:"Romosinuano"},
					{value:"Russian Black Pied", text:"Russian Black Pied"},
					{value:"RX3", text:"RX3"},
					{value:"Sahiwal", text:"Sahiwal"},
					{value:"Salers", text:"Salers"},
					{value:"Salorn", text:"Salorn"},
					{value:"Sanhe", text:"Sanhe"},
					{value:"Santa Cruz", text:"Santa Cruz"},
					{value:"Santa Gertrudis", text:"Santa Gertrudis"},
					{value:"San Martinero", text:"San Martinero"},
					{value:"Sarabi", text:"Sarabi"},
					{value:"Senepol", text:"Senepol"},
					{value:"Sharabi", text:"Sharabi"},
					{value:"Shetland", text:"Shetland"},
					{value:"Shorthorn", text:"Shorthorn"},
					{value:"Siboney", text:"Siboney"},
					{value:"Simbrah", text:"Simbrah"},
					{value:"Simmental", text:"Simmental"},
					{value:"Siri", text:"Siri"},
					{value:"Slovenian Cika", text:"Slovenian Cika"},
					{value:"South Devon", text:"South Devon"},
					{value:"Sussex", text:"Sussex"},
					{value:"Swedish Friesian", text:"Swedish Friesian"},
					{value:"Swedish Red-and-White", text:"Swedish Red-and-White"},
					{value:"Swedish Red Polled", text:"Swedish Red Polled"},
					{value:"Tarentaise", text:"Tarentaise"},
					{value:"Telemark", text:"Telemark"},
					{value:"Texas Longhorn", text:"Texas Longhorn"},
					{value:"Texon", text:"Texon"},
					{value:"Tharparkar", text:"Tharparkar"},
					{value:"Tswana", text:"Tswana"},
					{value:"Tuli", text:"Tuli"},
					{value:"Turkish Grey Steppe", text:"Turkish Grey Steppe"},
					{value:"Ukrainian Beef", text:"Ukrainian Beef"},
					{value:"Ukrainian Grey", text:"Ukrainian Grey"},
					{value:"Ukrainian Whitehead", text:"Ukrainian Whitehead"},
					{value:"Umblachery", text:"Umblachery"},
					{value:"Ural Black Pied", text:"Ural Black Pied"},
					{value:"Vestland Fjord", text:"Vestland Fjord"},
					{value:"Vestland Red Polled", text:"Vestland Red Polled"},
					{value:"Vosges", text:"Vosges"},
					{value:"Wagyu", text:"Wagyu"},
					{value:"Welsh Black", text:"Welsh Black"},
					{value:"White Cáceres", text:"White Cáceres"},
					{value:"White Park", text:"White Park"},
					{value:"Xinjiang Brown", text:"Xinjiang Brown"},
					{value:"Yanbian", text:"Yanbian"}];
										
animaldb["Horse"] = [{value:"Abyssinian", text:"Abyssinian"},
					{value:"Akhal Teke", text: "Akhal Teke"},
					{value:"Albanian", text: "Albanian"},
					{value:"Altai ", text: "Altai "},
					{value:"American Cream Draft ", text: "American Cream Draft "},
					{value:"American Creme and White ", text: "American Creme and White "},
					{value:"American Walking Pony ", text: "American Walking Pony "},
					{value:"Andalusian", text: "Andalusian"},
					{value:"Andravida", text: "Andravida"},
					{value:"Anglo-Kabarda", text: "Anglo-Kabarda"},
					{value:"Appaloosa", text: "Appaloosa"},
					{value:"Araappaloosa", text: "Araappaloosa"},
					{value:"Arabian", text: "Arabian"},
					{value:"Ardennes", text: "Ardennes"},
					{value:"Argentine Criollo", text: "Argentine Criollo"},
					{value:"Asturian", text: "Asturian"},
					{value:"Australian Brumby", text: "Australian Brumby"},
					{value:"Australian Stock Horse ", text: "Australian Stock Horse "},
					{value:"Azteca ", text: "Azteca "},
					{value:"Balearic", text: "Balearic"},
					{value:"Baluchi", text: "Baluchi"},
					{value:"Banker", text: "Banker"},
					{value:"Ban-ei", text: "Ban-ei"},
					{value:"Barb", text: "Barb"},
					{value:"Bashkir", text: "Bashkir"},
					{value:"Bashkir Curly", text: "Bashkir Curly"},
					{value:"Basotho Pony", text: "Basotho Pony"},
					{value:"Belgian", text: "Belgian"},
					{value:"Bhirum Pony", text: "Bhirum Pony"},
					{value:"Bhotia Pony", text: "Bhotia Pony"},
					{value:"Black Forest", text: "Black Forest"},
					{value:"Boer", text: "Boer"},
					{value:"Breton", text: "Breton"},
					{value:"Buckskin ", text: "Buckskin "},
					{value:"Budyonny ", text: "Budyonny "},
					{value:"Byelorussian Harness", text: "Byelorussian Harness"},
					{value:"Camargue", text: "Camargue"},
					{value:"Campolina", text: "Campolina"},
					{value:"Canadian", text: "Canadian"},
					{value:"Carthusian", text: "Carthusian"},
					{value:"Caspian", text: "Caspian"},
					{value:"Cayuse", text: "Cayuse"},
					{value:"Cheju", text: "Cheju"},
					{value:"Chilean Corralero", text: "Chilean Corralero"},
					{value:"Chincoteague Pony", text: "Chincoteague Pony"},
					{value:"Cleveland Bay ", text: "Cleveland Bay "},
					{value:"Clydesdale ", text: "Clydesdale "},
					{value:"Colorado Ranger Horse ", text: "Colorado Ranger Horse "},
					{value:"Connemara Pony", text: "Connemara Pony"},
					{value:"Criollo (Uruguay)", text: "Criollo (Uruguay)"},
					{value:"Crioulo", text: "Crioulo"},
					{value:"Dales Pony", text: "Dales Pony"},
					{value:"Danube", text: "Danube"},
					{value:"Dartmoor Pony", text: "Dartmoor Pony"},
					{value:"Deliboz", text: "Deliboz"},
					{value:"Djerma", text: "Djerma"},
					{value:"Døle", text: "Døle"},
					{value:"Dongola", text: "Dongola"},
					{value:"Dülmen Pony", text: "Dülmen Pony"},
					{value:"Dutch Draft ", text: "Dutch Draft "},
					{value:"Dutch Warmblood", text: "Dutch Warmblood"},
					{value:"East Bulgarian", text: "East Bulgarian"},
					{value:"Egyptian", text: "Egyptian"},
					{value:"Eriskay Pony", text: "Eriskay Pony"},
					{value:"Estonian Native ", text: "Estonian Native "},
					{value:"Exmoor Pony ", text: "Exmoor Pony "},
					{value:"Faeroes Pony", text: "Faeroes Pony"},
					{value:"Falabella", text: "Falabella"},
					{value:"Fell Pony", text: "Fell Pony"},
					{value:"Finnhorse", text: "Finnhorse"},
					{value:"Fleuve", text: "Fleuve"},
					{value:"Fouta", text: "Fouta"},
					{value:"Frederiksborg", text: "Frederiksborg"},
					{value:"French Saddlebred", text: "French Saddlebred"},
					{value:"French Trotter", text: "French Trotter"},
					{value:"Friesian", text: "Friesian"},
					{value:"Galiceño ", text: "Galiceño "},
					{value:"Galician Pony", text: "Galician Pony"},
					{value:"Gelderlander", text: "Gelderlander"},
					{value:"Gidran", text: "Gidran"},
					{value:"Golden American Saddlebred", text: "Golden American Saddlebred"},
					{value:"Gotland", text: "Gotland"},
					{value:"Groningen", text: "Groningen"},
					{value:"Guangxi", text: "Guangxi"},
					{value:"Hackney ", text: "Hackney "},
					{value:"Haflinger ", text: "Haflinger "},
					{value:"Hanoverian ", text: "Hanoverian "},
					{value:"Hequ", text: "Hequ"},
					{value:"Highland Pony", text: "Highland Pony"},
					{value:"Hokkaido", text: "Hokkaido"},
					{value:"Holsteiner", text: "Holsteiner"},
					{value:"Hucul", text: "Hucul"},
					{value:"Hungarian Warmblood", text: "Hungarian Warmblood"},
					{value:"Icelandic", text: "Icelandic"},
					{value:"Iomud", text: "Iomud"},
					{value:"Irish Draught", text: "Irish Draught"},
					{value:"Jinzhou", text: "Jinzhou"},
					{value:"Jutland", text: "Jutland"},
					{value:"Kabarda", text: "Kabarda"},
					{value:"Karabair", text: "Karabair"},
					{value:"Karabakh", text: "Karabakh"},
					{value:"Kazakh", text: "Kazakh"},
					{value:"Kerry Bog Pony", text: "Kerry Bog Pony"},
					{value:"Kiger Mustang", text: "Kiger Mustang"},
					{value:"Kirdi Pony", text: "Kirdi Pony"},
					{value:"Kisber Felver", text: "Kisber Felver"},
					{value:"Kiso", text: "Kiso"},
					{value:"Kladruby", text: "Kladruby"},
					{value:"Knabstrup", text: "Knabstrup"},
					{value:"Kushum", text: "Kushum"},
					{value:"Kustanai ", text: "Kustanai "},
					{value:"Latvian", text: "Latvian"},
					{value:"Lithuanian Heavy Draft", text: "Lithuanian Heavy Draft"},
					{value:"Lipizzan", text: "Lipizzan"},
					{value:"Lokai", text: "Lokai"},
					{value:"Losino", text: "Losino"},
					{value:"Lusitano", text: "Lusitano"},
					{value:"Malopolski", text: "Malopolski"},
					{value:"Mangalarga", text: "Mangalarga"},
					{value:"Marwari", text: "Marwari"},
					{value:"M'Bayar", text: "M'Bayar"},
					{value:"Mérens Pony", text: "Mérens Pony"},
					{value:"Messara", text: "Messara"},
					{value:"Miniature", text: "Miniature"},
					{value:"Misaki", text: "Misaki"},
					{value:"Missouri Fox Trotting Horse", text: "Missouri Fox Trotting Horse"},
					{value:"Miyako", text: "Miyako"},
					{value:"Mongolian", text: "Mongolian"},
					{value:"Morab ", text: "Morab "},
					{value:"Morgan", text: "Morgan"},
					{value:"Moyle", text: "Moyle"},
					{value:"Mustang", text: "Mustang"},
					{value:"Murgese", text: "Murgese"},
					{value:"National Show Horse", text: "National Show Horse"},
					{value:"New Forest Pony", text: "New Forest Pony"},
					{value:"New Kirgiz", text: "New Kirgiz"},
					{value:"Newfoundland Pony", text: "Newfoundland Pony"},
					{value:"Noma", text: "Noma"},
					{value:"Nooitgedacht Pony", text: "Nooitgedacht Pony"},
					{value:"Noric", text: "Noric"},
					{value:"Nordland", text: "Nordland"},
					{value:"Northeastern", text: "Northeastern"},
					{value:"North Swedish Horse ", text: "North Swedish Horse "},
					{value:"Norwegian Fjord ", text: "Norwegian Fjord "},
					{value:"Ob", text: "Ob"},
					{value:"Oldenburg ", text: "Oldenburg "},
					{value:"Orlov Trotter ", text: "Orlov Trotter "},
					{value:"Paint ", text: "Paint "},
					{value:"Palomino", text: "Palomino"},
					{value:"Pantaneiro", text: "Pantaneiro"},
					{value:"Paso Fino ", text: "Paso Fino "},
					{value:"Percheron", text: "Percheron"},
					{value:"Peruvian Paso", text: "Peruvian Paso"},
					{value:"Pindos Pony", text: "Pindos Pony"},
					{value:"Pinia", text: "Pinia"},
					{value:"Pintabian", text: "Pintabian"},
					{value:"Pinto", text: "Pinto"},
					{value:"Polish Konik", text: "Polish Konik"},
					{value:"Pony of the Americas", text: "Pony of the Americas"},
					{value:"Pottok", text: "Pottok"},
					{value:"Przewalski", text: "Przewalski"},
					{value:"Pyrenean Tarpan", text: "Pyrenean Tarpan"},
					{value:"Qatgani", text: "Qatgani"},
					{value:"Quarab", text: "Quarab"},
					{value:"Quarter Horse", text: "Quarter Horse"},
					{value:"Quarter Pony", text: "Quarter Pony"},
					{value:"Racking Horse ", text: "Racking Horse "},
					{value:"Rocky Mountain Horse ", text: "Rocky Mountain Horse "},
					{value:"Russian Don ", text: "Russian Don "},
					{value:"Russian Heavy Draft ", text: "Russian Heavy Draft "},
					{value:"Russian Trotter ", text: "Russian Trotter "},
					{value:"Saddlebred ", text: "Saddlebred "},
					{value:"Sanhe", text: "Sanhe"},
					{value:"Schleswiger Heavy Draft", text: "Schleswiger Heavy Draft"},
					{value:"Schwarzwälder Fuchs", text: "Schwarzwälder Fuchs"},
					{value:"Selle Francais ", text: "Selle Francais "},
					{value:"Shagya ", text: "Shagya "},
					{value:"Shetland Pony", text: "Shetland Pony"},
					{value:"Shire", text: "Shire"},
					{value:"Single-Footing Horse", text: "Single-Footing Horse"},
					{value:"Skyros Pony", text: "Skyros Pony"},
					{value:"Somali Pony", text: "Somali Pony"},
					{value:"Sorraia", text: "Sorraia"},
					{value:"Soviet Heavy Draft ", text: "Soviet Heavy Draft "},
					{value:"Spanish Mustang ", text: "Spanish Mustang "},
					{value:"Spanish-Barb ", text: "Spanish-Barb "},
					{value:"Spanish-Norman ", text: "Spanish-Norman "},
					{value:"Standardbred", text: "Standardbred"},
					{value:"Sudan Country-Bred", text: "Sudan Country-Bred"},
					{value:"Suffolk", text: "Suffolk"},
					{value:"Swedish Warmblood", text: "Swedish Warmblood"},
					{value:"Taishuh", text: "Taishuh"},
					{value:"Tarpan", text: "Tarpan"},
					{value:"Tawleed", text: "Tawleed"},
					{value:"Tennessee Walking Horse", text: "Tennessee Walking Horse"},
					{value:"Tersk", text: "Tersk"},
					{value:"Thessalian", text: "Thessalian"},
					{value:"Thoroughbred", text: "Thoroughbred"},
					{value:"Tokara", text: "Tokara"},
					{value:"Tori", text: "Tori"},
					{value:"Trakehner", text: "Trakehner"},
					{value:"Ukrainian Saddle", text: "Ukrainian Saddle"},
					{value:"Vlaamperd", text: "Vlaamperd"},
					{value:"Vladimir Heavy Draft", text: "Vladimir Heavy Draft"},
					{value:"Vyatka ", text: "Vyatka "},
					{value:"Welara Pony", text: "Welara Pony"},
					{value:"Welsh Pony and Cob", text: "Welsh Pony and Cob"},
					{value:"West African Barb", text: "West African Barb"},
					{value:"Western Sudan Pony", text: "Western Sudan Pony"},
					{value:"Wielkopolski", text: "Wielkopolski"},
					{value:"Xilingol ", text: "Xilingol "},
					{value:"Yakut", text: "Yakut"},
					{value:"Yanqi", text: "Yanqi"},
					{value:"Yili", text: "Yili"},
					{value:"Yonaguni ", text: "Yonaguni "},
					{value:"Zaniskari Pony", text: "Zaniskari Pony"},
					{value:"Zhemaichu", text: "Zhemaichu"}];
					
animaldb["Chicken"] = [{value:"Not Applicable", text:"Not Applicable"}];
										
animaldb["Pig"] = [{value:"American Landrace", text: "American Landrace"},
					{value:"American Yorkshire", text: "American Yorkshire"},
					{value:"Angeln Saddleback", text: "Angeln Saddleback"},
					{value:"Arapawa Island", text: "Arapawa Island"},
					{value:"Ba Xuyen", text: "Ba Xuyen"},
					{value:"Bantu", text: "Bantu"},
					{value:"Bazna", text: "Bazna"},
					{value:"Beijing Black", text: "Beijing Black"},
					{value:"Belarus Black Pied", text: "Belarus Black Pied"},
					{value:"Belgian Landrace", text: "Belgian Landrace"},
					{value:"Bentheim Black Pied", text: "Bentheim Black Pied"},
					{value:"Berkshire", text: "Berkshire"},
					{value:"Black Slavonian", text: "Black Slavonian"},
					{value:"British Landrace", text: "British Landrace"},
					{value:"British Lop", text: "British Lop"},
					{value:"Bulgarian White ", text: "Bulgarian White"},
					{value:"Cantonese", text: "Cantonese"},
					{value:"Chester White", text: "Chester White"},
					{value:"Czech Improved White ", text: "Czech Improved White"},
					{value:"Danish Landrace", text: "Danish Landrace"},
					{value:"Dermantsi Pied", text: "Dermantsi Pied"},
					{value:"Duroc", text: "	Duroc"},
					{value:"Dutch Landrace", text: "Dutch Landrace"},
					{value:"Fengjing", text: "	Fengjing"},
					{value:"Finnish Landrace", text: "Finnish Landrace"},
					{value:"French Landrace", text: "French Landrace"},
					{value:"German Landrace", text: "German Landrace"},
					{value:"Gloucestershire Old Spots", text: "Gloucestershire Old Spots"},
					{value:"Guinea Hog", text: "Guinea Hog"},
					{value:"Hampshire", text: "Hampshire"},
					{value:"Hereford", text: "Hereford"},
					{value:"Hezuo", text: "Hezuo"},
					{value:"Iberian", text: "Iberian"},
					{value:"Italian Landrace", text: "Italian Landrace"},
					{value:"Jinhua", text: "Jinhua"},
					{value:"Kele", text: "Kele"},
					{value:"Krskopolje", text: "Krskopolje"},
					{value:"Kunekune", text: "Kunekune"},
					{value:"Lacombe", text: "Lacombe"},
					{value:"Large Black", text: "Large Black"},
					{value:"Large Black-white", text: "Large Black-white"},
					{value:"Large White", text: "Large White"},
					{value:"Lithuanian Native", text: "Lithuanian Native"},
					{value:"Mangalitsa", text: "Mangalitsa"},
					{value:"Meishan", text: "Meishan"},
					{value:"Middle White", text: "Middle White"},
					{value:"Minzhu", text: "Minzhu"},
					{value:"Mong Cai", text: "Mong Cai"},
					{value:"Mukota", text: "Mukota"},
					{value:"Mora Romagnola", text: "Mora Romagnola"},
					{value:"Moura", text: "Moura"},
					{value:"Mulefoot", text: "Mulefoot"},
					{value:"Neijiang", text: "Neijiang"},
					{value:"Ningxiang", text: "Ningxiang"},
					{value:"Norwegian Landrace", text: "Norwegian Landrace"},
					{value:"Ossabaw Island", text: "Ossabaw Island"},
					{value:"Oxford Sandy and Black", text: "Oxford Sandy and Black"},
					{value:"Philippine Native", text: "Philippine Native"},
					{value:"Pietrain", text: "	Pietrain"},
					{value:"Poland China", text: "Poland China"},
					{value:"Red Wattle", text: "Red Wattle"},
					{value:"Saddleback", text: "Saddleback"},
					{value:"Spots", text: "Spots"},
					{value:"Swabian-Hall", text: "Swabian-Hall"},
					{value:"Swedish Landrace", text: "Swedish Landrace"},
					{value:"Tamworth", text: "Tamworth"},
					{value:"Thuoc Nhieu", text: "Thuoc Nhieu"},
					{value:"Tibetan", text: "	Tibetan"},
					{value:"Turopolje", text: "Turopolje"},
					{value:"Vietnamese Potbelly", text: "Vietnamese Potbelly"},
					{value:"Welsh", text: "Welsh"},
					{value:"Wuzhishan", text: "Wuzhishan"}];
 
animaldb["Sheep"] = [{value:"Acipayam", text: "Acipayam"},
					{value:"Adal", text: "Adal"},
					{value:"Afghan Arabi", text: "Afghan Arabi"},
					{value:"Africana", text: "Africana"},
					{value:"African Blackhead", text: "African Blackhead"},
					{value:"Alai", text: "Alai"},
					{value:"Alcarreña", text: "Alcarreña"},
					{value:"Algarve Churro", text: "Algarve Churro"},
					{value:"Algerian Arab", text: "Algerian Arab"},
					{value:"Altai", text: "Altai"},
					{value:"Altay", text: "Altay"},
					{value:"American Blackbelly", text: "American Blackbelly"},
					{value:"Apennine", text: "Apennine"},
					{value:"Arabi", text: "Arabi"},
					{value:"Arapawa Island", text: "Arapawa Island"},
					{value:"Argentine Merino", text: "Argentine Merino"},
					{value:"Arles Merino", text: "Arles Merino"},
					{value:"Armenian Semicoarsewool", text: "Armenian Semicoarsewool"},
					{value:"Askanian", text: "Askanian"},
					{value:"Awassi", text: "Awassi"},
					{value:"Balkhi", text: "Balkhi"},
					{value:"Baluchi", text: "Baluchi"},
					{value:"Balwen Welsh Mountain", text: "Balwen Welsh Mountain"},
					{value:"Barbado", text: "Barbado"},
					{value:"Barbados Blackbelly", text: "Barbados Blackbelly"},
					{value:"Basco-Béarnais", text: "Basco-Béarnais"},
					{value:"Bavarian Forest", text: "Bavarian Forest"},
					{value:"Bentheimer Landschaf", text: "Bentheimer Landschaf"},
					{value:"Bergamasca", text: "Bergamasca"},
					{value:"Beulah Speckled-Face", text: "Beulah Speckled-Face"},
					{value:"Bibrik", text: "Bibrik"},
					{value:"Biellese", text: "Biellese"},
					{value:"Black Welsh Mountain Sheep", text: "Black Welsh Mountain Sheep"},
					{value:"Bleu du Maine", text: "Bleu du Maine"},
					{value:"Bluefaced Leicester", text: "Bluefaced Leicester"},
					{value:"Bond", text: "Bond"},
					{value:"Booroola Merino", text: "Booroola Merino"},
					{value:"Border Leicester", text: "Border Leicester"},
					{value:"Boreray", text: "Boreray"},
					{value:"Bovska", text: "Bovska"},
					{value:"Braunes Bergschaf", text: "Braunes Bergschaf"},
					{value:"Brazilian Somali", text: "Brazilian Somali"},
					{value:"Brecknock Hill Cheviot", text: "Brecknock Hill Cheviot"},
					{value:"Brillenschaf", text: "Brillenschaf"},
					{value:"British Milk Sheep", text: "British Milk Sheep"},
					{value:"Bündner Oberland", text: "Bündner Oberland"},
					{value:"California Red", text: "California Red"},
					{value:"California Variegated Mutant", text: "California Variegated Mutant"},
					{value:"Campanian Barbary", text: "Campanian Barbary"},
					{value:"Castlemilk Moorit", text: "Castlemilk Moorit"},
					{value:"Cine Capari", text: "Cine Capari"},
					{value:"Charollais", text: "Charollais"},
					{value:"Cheviot", text: "Cheviot"},
					{value:"Chios", text: "Chios"},
					{value:"Cholistani", text: "Cholistani"},
					{value:"Clun Forest", text: "Clun Forest"},
					{value:"Coburger Fuchsschaf", text: "Coburger Fuchsschaf"},
					{value:"Columbia", text: "Columbia"},
					{value:"Comeback", text: "Comeback"},
					{value:"Comisana", text: "Comisana"},
					{value:"Coopworth", text: "Coopworth"},
					{value:"Cormo", text: "Cormo"},
					{value:"Corriedale", text: "Corriedale"},
					{value:"Cotswold", text: "Cotswold"},
					{value:"Criollo", text: "Criollo"},
					{value:"Dala", text: "Dala"},
					{value:"Dalesbred", text: "Dalesbred"},
					{value:"Dagliç", text: "Dagliç"},
					{value:"Damani", text: "Damani"},
					{value:"Damara", text: "Damara"},
					{value:"Danish Landrace", text: "Danish Landrace"},
					{value:"Dartmoor", text: "Dartmoor"},
					{value:"Debouillet", text: "Debouillet"},
					{value:"Delaine Merino", text: "Delaine Merino"},
					{value:"Deutsches Blaukoepfiges Fleischschaf", text: "Deutsches Blaukoepfiges Fleischschaf"},
					{value:"Dorper", text: "Dorper"},
					{value:"Derbyshire Gritstone", text: "Derbyshire Gritstone"},
					{value:"Devon Closewool", text: "Devon Closewool"},
					{value:"Devon Longwoolled", text: "Devon Longwoolled"},
					{value:"Dorset", text: "Dorset"},
					{value:"Dorset Down", text: "Dorset Down"},
					{value:"Drysdale", text: "Drysdale"},
					{value:"Elliottdale", text: "Elliottdale"},
					{value:"Exmoor Horn", text: "Exmoor Horn"},
					{value:"Fabrianese", text: "Fabrianese"},
					{value:"Faeroes", text: "Faeroes"},
					{value:"Finnsheep", text: "Finnsheep"},
					{value:"Fonthill Merino", text: "Fonthill Merino"},
					{value:"Friesian Milk Sheep", text: "Friesian Milk Sheep"},
					{value:"Galway", text: "Galway"},
					{value:"Gansu Alpine Fine-wool", text: "Gansu Alpine Fine-wool"},
					{value:"Gentile di Puglia", text: "Gentile di Puglia"},
					{value:"German Blackheaded Mutton", text: "German Blackheaded Mutton"},
					{value:"German Mountain", text: "German Mountain"},
					{value:"German Mutton Merino", text: "German Mutton Merino"},
					{value:"German Whiteheaded Mutton", text: "German Whiteheaded Mutton"},
					{value:"Ghezel", text: "Ghezel"},
					{value:"Gökçeada", text: "Gökçeada"},
					{value:"Gotland", text: "Gotland"},
					{value:"Graue Gehoernte Heidschnucke", text: "Graue Gehoernte Heidschnucke"},
					{value:"Gromark", text: "Gromark"},
					{value:"Gulf Coast", text: "Gulf Coast"},
					{value:"Gute", text: "Gute"},
					{value:"Hampshire", text: "Hampshire"},
					{value:"Han", text: "Han"},
					{value:"Harnai", text: "Harnai"},
					{value:"Hasht Nagri", text: "Hasht Nagri"},
					{value:"Hazaragie", text: "Hazaragie"},
					{value:"Hebridean", text: "Hebridean"},
					{value:"Herdwick", text: "Herdwick"},
					{value:"Herik", text: "Herik"},
					{value:"Hill Radnor", text: "Hill Radnor"},
					{value:"Hog Island Sheep", text: "Hog Island Sheep"},
					{value:"Hu", text: "Hu"},
					{value:"Icelandic", text: "Icelandic"},
					{value:"Ile-de-France", text: "Ile-de-France"},
					{value:"Istrian Milk", text: "Istrian Milk"},
					{value:"Jacob", text: "Jacob"},
					{value:"Jezerskosolcavska", text: "Jezerskosolcavska"},
					{value:"Kachhi", text: "Kachhi"},
					{value:"Kajli", text: "Kajli"},
					{value:"Karacabey Merino", text: "Karacabey Merino"},
					{value:"Karakul", text: "Karakul"},
					{value:"Karayaka", text: "Karayaka"},
					{value:"Katahdin", text: "Katahdin"},
					{value:"Kerry Hill", text: "Kerry Hill"},
					{value:"Kivircik", text: "Kivircik"},
					{value:"Kooka", text: "Kooka"},
					{value:"Landais", text: "Landais"},
					{value:"Langhe", text: "Langhe"},
					{value:"Lati", text: "Lati"},
					{value:"Leicester Longwool", text: "Leicester Longwool"},
					{value:"Leineschaf", text: "Leineschaf"},
					{value:"Lincoln", text: "Lincoln"},
					{value:"Llanwenog", text: "Llanwenog"},
					{value:"Lleyn", text: "Lleyn"},
					{value:"Lohi", text: "Lohi"},
					{value:"Lonk", text: "Lonk"},
					{value:"Luzein", text: "Luzein"},
					{value:"Maltese", text: "Maltese"},
					{value:"Manchega", text: "Manchega"},
					{value:"Manech", text: "Manech"},
					{value:"Manx Loaghtan", text: "Manx Loaghtan"},
					{value:"Masai", text: "Masai"},
					{value:"Massese", text: "Massese"},
					{value:"Medium-Wool Merino", text: "Medium-Wool Merino"},
					{value:"Mehraban", text: "Mehraban"},
					{value:"Merinizzata italiana", text: "Merinizzata italiana"},
					{value:"Merinolandschaf", text: "Merinolandschaf"},
					{value:"Moghani", text: "Moghani"},
					{value:"Montadale", text: "Montadale"},
					{value:"Morada Nova", text: "Morada Nova"},
					{value:"Mouflon ", text: "Mouflon "},
					{value:"Navajo-Churro", text: "Navajo-Churro"},
					{value:"Nellore", text: "Nellore"},
					{value:"Norfolk Horn", text: "Norfolk Horn"},
					{value:"North Country Cheviot", text: "North Country Cheviot"},
					{value:"North Ronaldsay", text: "North Ronaldsay"},
					{value:"Norwegian Fur", text: "Norwegian Fur"},
					{value:"Old Norwegian", text: "Old Norwegian"},
					{value:"Orkney", text: "Orkney"},
					{value:"Ossimi", text: "Ossimi"},
					{value:"Oxford", text: "Oxford"},
					{value:"Pag Island", text: "Pag Island"},
					{value:"Pagliarola", text: "Pagliarola"},
					{value:"Pelibüey", text: "Pelibüey"},
					{value:"Perendale", text: "Perendale"},
					{value:"Pinzirita", text: "Pinzirita"},
					{value:"Pitt Island", text: "Pitt Island"},
					{value:"Poll Merino", text: "Poll Merino"},
					{value:"Polwarth", text: "Polwarth"},
					{value:"Polypay", text: "Polypay"},
					{value:"Pomeranian Coarsewool", text: "Pomeranian Coarsewool"},
					{value:"Portland", text: "Portland"},
					{value:"Priangan", text: "Priangan"},
					{value:"Qashqai", text: "Qashqai"},
					{value:"Qinghai Black Tibetan", text: "Qinghai Black Tibetan"},
					{value:"Qinghai Semifinewool", text: "Qinghai Semifinewool"},
					{value:"Quadrella", text: "Quadrella"},
					{value:"Quanglin Large-tail ", text: "Quanglin Large-tail "},
					{value:"Rabo Largo", text: "Rabo Largo"},
					{value:"Racka", text: "Racka"},
					{value:"Rambouillet", text: "Rambouillet"},
					{value:"Rasa Aragonesa", text: "Rasa Aragonesa"},
					{value:"Red Engadine", text: "Red Engadine"},
					{value:"Red Karaman", text: "Red Karaman"},
					{value:"Rhoenschaf", text: "Rhoenschaf"},
					{value:"Rideau Arcott", text: "Rideau Arcott"},
					{value:"Romanov", text: "Romanov"},
					{value:"Romney", text: "Romney"},
					{value:"Rouge de l'Ouest", text: "Rouge de l'Ouest"},
					{value:"Rouge de Roussillon", text: "Rouge de Roussillon"},
					{value:"Rough Fell", text: "Rough Fell"},
					{value:"Royal White", text: "Royal White"},
					{value:"Rya", text: "Rya"},
					{value:"Ryeland", text: "Ryeland"},
					{value:"Rygja", text: "Rygja"},
					{value:"Sahel-type", text: "Sahel-type"},
					{value:"Sakiz", text: "Sakiz"},
					{value:"Santa Cruz", text: "Santa Cruz"},
					{value:"Santa Inês", text: "Santa Inês"},
					{value:"Sardinian", text: "Sardinian"},
					{value:"Sar Planina", text: "Sar Planina"},
					{value:"Scottish Blackface", text: "Scottish Blackface"},
					{value:"Shetland", text: "Shetland"},
					{value:"Shropshire", text: "Shropshire"},
					{value:"Sicilian Barbary", text: "Sicilian Barbary"},
					{value:"Skudde", text: "Skudde"},
					{value:"Soay", text: "Soay"},
					{value:"Somali", text: "Somali"},
					{value:"Sopravissana", text: "Sopravissana"},
					{value:"South African Merino", text: "South African Merino"},
					{value:"South African Mutton Merino", text: "South African Mutton Merino"},
					{value:"South Devon", text: "South Devon"},
					{value:"South Suffolk", text: "South Suffolk"},
					{value:"Southdown", text: "Southdown"},
					{value:"South Wales Mountain", text: "South Wales Mountain"},
					{value:"Spælsau", text: "Spælsau"},
					{value:"Spiegel", text: "Spiegel"},
					{value:"St. Croix (Virgin Island White)", text: "St. Croix (Virgin Island White)"},
					{value:"Steigar", text: "Steigar"},
					{value:"Steinschaf", text: "Steinschaf"},
					{value:"Strong Wool Merino", text: "Strong Wool Merino"},
					{value:"Suffolk", text: "Suffolk"},
					{value:"Sumavska", text: "Sumavska"},
					{value:"Swaledale", text: "Swaledale"},
					{value:"Swedish Fur Sheep", text: "Swedish Fur Sheep"},
					{value:"Swiss Black-Brown Mountain", text: "Swiss Black-Brown Mountain"},
					{value:"Swiss White Alpine", text: "Swiss White Alpine"},
					{value:"Targhee", text: "Targhee"},
					{value:"Teeswater", text: "Teeswater"},
					{value:"Texel", text: "Texel"},
					{value:"Thalli", text: "Thalli"},
					{value:"Tong", text: "Tong"},
					{value:"Touabire", text: "Touabire"},
					{value:"Tsurcana", text: "Tsurcana"},
					{value:"Tunis", text: "Tunis"},
					{value:"Tuj", text: "Tuj"},
					{value:"Türkgeldi", text: "Türkgeldi"},
					{value:"Tyrol Mountain", text: "Tyrol Mountain"},
					{value:"Uda", text: "Uda"},
					{value:"Ujumqin", text: "Ujumqin"},
					{value:"Ushant ", text: "Ushant "},
					{value:"Valais Blacknose", text: "Valais Blacknose"},
					{value:"Van Rooy", text: "Van Rooy"},
					{value:"Vendéen", text: "Vendéen"},
					{value:"Walachenschaf", text: "Walachenschaf"},
					{value:"Wallis Country Sheep", text: "Wallis Country Sheep"},
					{value:"Waziri", text: "Waziri"},
					{value:"Weisse Hornlose Heidschnucke", text: "Weisse Hornlose Heidschnucke"},
					{value:"Welsh Hill Speckled Face", text: "Welsh Hill Speckled Face"},
					{value:"Welsh Mountain", text: "Welsh Mountain"},
					{value:"Welsh Mountain Badger Faced", text: "Welsh Mountain Badger Faced"},
					{value:"Wensleydale", text: "Wensleydale"},
					{value:"West African Dwarf", text: "West African Dwarf"},
					{value:"White Horned Heath Sheep", text: "White Horned Heath Sheep"},
					{value:"White Karaman", text: "White Karaman"},
					{value:"White Suffolk", text: "White Suffolk"},
					{value:"Whiteface Dartmoor", text: "Whiteface Dartmoor"},
					{value:"Whiteface Woodland", text: "Whiteface Woodland"},
					{value:"Wiltshire Horn", text: "Wiltshire Horn"},
					{value:"Xalda", text: "Xalda"},
					{value:"Xaxi Ardia", text: "Xaxi Ardia"},
					{value:"Xinjiang Finewool", text: "Xinjiang Finewool"},
					{value:"Yankasa", text: "Yankasa"},
					{value:"Yemeni", text: "Yemeni"},
					{value:"Yemen White", text: "Yemen White"},
					{value:"Yiecheng", text: "Yiecheng"},
					{value:"Yoroo", text: "Yoroo"},
					{value:"Yunnan Semifinewool", text: "Yunnan Semifinewool"},
					{value:"Zaghawa", text: "Zaghawa"},
					{value:"Zagoria", text: "Zagoria"},
					{value:"Zaian", text: "Zaian"},
					{value:"Zaïre Long-legged", text: "Zaïre Long-legged"},
					{value:"Zakynthos", text: "Zakynthos"},
					{value:"Zeeland Milk", text: "Zeeland Milk"},
					{value:"Zel", text: "Zel"},
					{value:"Zelazna", text: "Zelazna"},
					{value:"Zemmour", text: "Zemmour"},
					{value:"Zeta Yellow", text: "Zeta Yellow"},
					{value:"Zlatusha", text: "Zlatusha"},
					{value:"Zoulay", text: "Zoulay"}];

animaldb["Poultry"] = [{value:"Hen", text:"Hen"},
					{value:"Duck", text:"Duck"},
					{value:"Pigeon", text:"Pigeon"}];	

animaldb["Other"] = [{value:"Not Applicable", text:"Not Applicable"}];	
					
animaldb["Animal"] = [{value:"Breed 1", text:"Breed 1"},
					{value:"Breed 2", text:"Breed 2"},
					{value:"Breed 3", text:"Breed 3"}];	
					
					
					
function setAnimalBreed(chooser) {
    var newElem;
    var where = (navigator.appName == "Microsoft Internet Explorer") ? -1 : null;
    var modelChooser = chooser.form.elements["breed"];
    while (modelChooser.options.length) {
        modelChooser.remove(0);
    }
    var choice = chooser.options[chooser.selectedIndex].value;
    var db = animaldb[choice];
    newElem = document.createElement("option");
	if (choice == "Select Animal"){
		newElem.text = "Select Breed";
		newElem.value = "";
		modelChooser.add(newElem, where);
		}
    if (choice != "") {
        for (var i = 0; i < db.length; i++) {
            newElem = document.createElement("option");
            newElem.text = db[i].text;
            newElem.value = db[i].value;
            modelChooser.add(newElem, where);
        }
    }
}